import { supabaseAdmin } from './admin-client'
import { loadAiConfig } from './config'
import { buildConversationContext } from './context'
import { retrieveKnowledge } from './knowledge'
import { generateReply } from './generate'
import { buildSystemPrompt } from './defaults'
import { logAiUsage } from './usage'
import { latestUserMessage } from './query'
import {
  AI_TOOLS,
  executeToolCall,
  extractBookingResult,
  loadContactContext,
  type BookingToolResult,
} from './tools'
import { calendarConfigured, MEET_FALLBACK_LINK } from '@/lib/calendar'
import { gmailConfigured } from '@/lib/gmail'
import { engineSendAiReply } from '@/lib/flows/meta-send'
import { checkRateLimit, RATE_LIMITS } from '@/lib/rate-limit'
import type { ChatMessage } from './types'

/** Maximum tool-call rounds per inbound to avoid infinite loops. */
const MAX_TOOL_ROUNDS = 3

/**
 * Customer-facing fallback when a scheduling tool ran but we could not
 * produce a confirmation with a Meet link (tool threw, or the model ran
 * out of rounds). Sent instead of leaving the customer in silence.
 */
export const AGENDAR_FALLBACK_MESSAGE =
  'Tu cita ha sido procesada, pero tuvimos un inconveniente generando el enlace de Google Meet. Un asesor te contactará en breve.'

/**
 * Deterministic, customer-facing booking confirmation built from the REAL
 * agendar_cita tool result (fecha/hora/link) — it does not depend on the
 * model echoing the link back. Dispatched by the backend the instant a
 * booking succeeds, so a booked appointment ALWAYS reaches the customer
 * in ONE bubble (the sender is told to skip its paragraph splitter). The
 * Google Meet URL is MANDATORY: it uses the real link returned by the
 * tool (hangoutLink/entryPoints/htmlLink) or the MEET_FALLBACK_LINK —
 * the message is never sent without a URL.
 * Returns null when the booking was not confirmed.
 */
export function buildBookingConfirmationMessage(
  booking: BookingToolResult,
  contactName?: string | null,
): string | null {
  if (booking.confirmado !== true) return null
  const nombre = contactName?.trim() || 'Humberto'
  const fecha = booking.fecha ?? (booking.inicio?.slice(0, 10) ?? '')
  const hora = booking.hora ?? (booking.inicio?.slice(11, 16) ?? '')
  const link = booking.link || MEET_FALLBACK_LINK
  return `¡Listo, ${nombre}! Tu cita ha sido agendada con éxito para el ${fecha} a las ${hora}.\n\nPuedes unirte a la videollamada de Google Meet directamente desde este enlace:\n${link}`
}

/**
 * Google Meet / Google Calendar URL patterns that ONLY the real tool
 * output may contain. Any occurrence generated by the model is fake.
 */
const FAKE_LINK_SRC =
  'https?:\\/\\/(?:meet\\.google\\.com\\/[\\w-]+|calendar\\.google\\.com\\/event[^\\s"\\)]*)'
const FAKE_LINK_RE = new RegExp(FAKE_LINK_SRC, 'gi')
const FAKE_LINK_DETECT = new RegExp(FAKE_LINK_SRC, 'i')

/** Phrases the model uses for a "wait, I'm on it" message WHILE NO tool
 *  has actually run. Under the no-repetitive-intermediate rule these are
 *  not acceptable as the final WhatsApp message for a booking request. */
const INTERMEDIATE_ACK_RE =
  /un momento|en un momento|un instante|enseguida|estoy registrando|estoy agendando|estoy confirmando|estoy revisando|estoy verificando|d[eé]jame (?:revisar|verificar|ver|consultar|agendar)|ya te (?:confirmo|aviso|digo)|ya mismo|por favor espera|espera un moment|perm[ií]teme|un segundo/i

/** Phrases that PROMISE a Meet/meeting link. A final WhatsApp message
 *  containing one of these but no REAL link (from the tool result) would
 *  go out as a dangling "aquí está el enlace:" — never send that. */
const LINK_PROMISE_RE =
  /este es el enlace|aqu[ií] tienes el enlace|a trav[eé]s de este enlace|para que te conectes|para acceder a (?:la|tu) (?:videollamada|reuni[oó]n|llamada)|[uú]nete a (?:la|tu) (?:videollamada|reuni[oó]n|llamada)|(?:el|este) enlace de (?:Google )?Meet\s*:/i

/** Booking signals in the conversation: an ack/claim is only intercepted
 *  when the customer is actually trying to schedule. */
const BOOKING_INTENT_RE =
  /\bcita\b|agendar|reagendar|reuni[oó]n|horario|disponible|disponibilidad|a qu[eé] hora|qu[eé] horario|consult(?:a|ar|aci[oó]n)|valoraci[oó]n|ma[nñ]ana a las|hoy a las|semana que viene/i

function hasBookingIntent(messages: ChatMessage[]): boolean {
  return messages.some(
    (m) =>
      typeof m.content === 'string' && BOOKING_INTENT_RE.test(m.content),
  )
}

function looksLikeBookingConfirmation(text: string): boolean {
  if (!/\bcita\b/i.test(text)) return false
  if (FAKE_LINK_DETECT.test(text)) return true
  return /agend(?:ad[oa]|é|amos)|confirm(?:ad[oa]|ada)|qued(?:ó|o)\s+/i.test(
    text,
  )
}

/**
 * Deterministic guard against hallucinated bookings. Runs on the final
 * message BEFORE it is sent:
 *  - real agendar_cita success + link  → replace every Meet/calendar URL
 *    with that link (append it if the model omitted it),
 *  - real success but no link         → use MEET_FALLBACK_LINK, keeping a
 *    Google Meet URL in any confirmation,
 *  - no real success this turn: never promise a booking. When the text
 *    claims a booking (and the customer was trying to schedule) OR is an
 *    intermediate "un momento…" wait message (always, booking or not)
 *    return null so the caller skips the turn without muting; anything
 *    else keeps its fake URLs stripped.
 */
export function guardBookingReply(
  text: string,
  booking: BookingToolResult | null,
  opts: { bookingContext?: boolean } = {},
): string | null {
  if (!text) return text

  const confirmed = booking?.confirmado === true
  // Un mensaje de confirmación NUNCA queda sin URL: el link real si la
  // tool lo devolvió, si no el fallback de Meet.
  const resolvedLink: string = booking?.link || MEET_FALLBACK_LINK

  if (confirmed) {
    const replaced = text.replace(FAKE_LINK_RE, resolvedLink)
    return replaced.includes(resolvedLink)
      ? replaced
      : `${replaced}\nAquí tienes el enlace de tu reunión: ${resolvedLink}`
  }

  // NUNCA enviar un texto que prometa un enlace de Meet/meeting sin que la
  // tool lo haya devuelto: "Este es el enlace de Google Meet para que te
  // conectes:" sin URL sería una burbuja vacía.
  if (LINK_PROMISE_RE.test(text)) return null
  if (INTERMEDIATE_ACK_RE.test(text)) return null
  if (opts.bookingContext ?? false) {
    if (looksLikeBookingConfirmation(text)) return null
  }
  return text.replace(FAKE_LINK_RE, '')
}

interface DispatchArgs {
  accountId: string
  conversationId: string
  contactId: string
  configOwnerUserId: string
  /** Meta id (wamid) of the inbound message being answered — used to
   *  keep WhatsApp's typing indicator alive across the multi-part reply. */
  composeMessageId?: string
}

/**
 * AI auto-reply for a freshly-arrived inbound message.
 *
 * Invoked from the WhatsApp webhook's `after()` block, only when no
 * deterministic flow consumed the message (flows win). Mirrors the flow
 * runner's contract: it owns its try/catch and NEVER throws — a failing
 * or slow LLM call must not affect the webhook's 200 to Meta.
 */
export async function dispatchInboundToAiReply(
  args: DispatchArgs,
): Promise<void> {
  const { accountId, conversationId, contactId, configOwnerUserId } = args

  try {
    const db = supabaseAdmin()

    const config = await loadAiConfig(db, accountId)
    if (!config || !config.autoReplyEnabled) return

    const { data: autoResponders } = await db
      .from('automations')
      .select('id')
      .eq('account_id', accountId)
      .eq('is_active', true)
      .in('trigger_type', ['new_message_received', 'keyword_match'])
      .limit(1)
    if (autoResponders && autoResponders.length > 0) return

    const { data: conv, error: convErr } = await db
      .from('conversations')
      .select('assigned_agent_id')
      .eq('id', conversationId)
      .maybeSingle()
    if (convErr || !conv) return
    // Único criterio de silencio: un humano que tomó el control. No existe
    // flag de pausa ni de handoff (ai_autoreply_disabled) ni límite de
    // respuestas: mientras no haya agente asignado, la IA responde SIEMPRE
    // cada mensaje entrante ("Hola", "?", etc.) sin dejar en visto.
    if (conv.assigned_agent_id) return

    const messages = await buildConversationContext(db, conversationId)
    if (messages.length === 0) return

    const acctLimit = checkRateLimit(
      `ai-autoreply:${accountId}`,
      RATE_LIMITS.aiAutoReplyAccount,
    )
    if (!acctLimit.success) {
      console.warn(
        `[ai auto-reply] account ${accountId} hit the per-account rate limit — skipping this inbound.`,
      )
      return
    }

    // Pre-LLM context is fetched in parallel (knowledge retrieval and
    // the contact profile/citas are independent) so the reply isn't held
    // for two sequential DB + embedding round trips.
    const [knowledge, contactCtx] = await Promise.all([
      retrieveKnowledge(
        db,
        accountId,
        config,
        latestUserMessage(messages),
      ),
      loadContactContext(db, contactId),
    ])

    const systemPrompt = buildSystemPrompt({
      userPrompt: config.systemPrompt,
      mode: 'auto_reply',
      knowledge,
      contactName: contactCtx?.name,
      contactEmail: contactCtx?.email,
      contactLocation: contactCtx?.location,
      calendarEnabled: calendarConfigured(),
      gmailEnabled: gmailConfigured(),
      citas: contactCtx?.citas,
    })

    // Tool execution loop: the model may request tool calls before
    // producing a final text reply. We feed tool results back and
    // re-generate up to MAX_TOOL_ROUNDS times.
    let finalText: string | null = ''
    let finalUsage = null
    let toolFallback: string | null = null
    // Latest REAL successful booking from agendar_cita's JSON_RESULT.
    // Everything else that looks like a confirmation is hallucination.
    let realBooking: BookingToolResult | null = null
    const conversationMessages: ChatMessage[] = [...messages]

    for (let round = 0; round <= MAX_TOOL_ROUNDS; round++) {
      const result = await generateReply({
        config,
        systemPrompt,
        messages: conversationMessages,
        tools: AI_TOOLS,
      })

      finalUsage = result.usage

      // If the model returned tool calls, execute them and continue.
      if (result.toolCalls && result.toolCalls.length > 0) {
        const toolResults: ChatMessage[] = []
        for (const tc of result.toolCalls) {
          let output: string
          try {
            output = await executeToolCall(db, accountId, contactId, tc)
          } catch (err) {
            // A thrown tool must never abort the whole turn — that would
            // leave the customer with no message at all. Turn the failure
            // into a tool result the model can relay, and remember a
            // deterministic fallback for the scheduling case.
            console.error(`[ai auto-reply] tool "${tc.name}" threw:`, err)
            if (tc.name === 'agendar_cita') {
              toolFallback = AGENDAR_FALLBACK_MESSAGE
            }
            output =
              tc.name === 'agendar_cita'
                ? AGENDAR_FALLBACK_MESSAGE
                : `Error: la herramienta ${tc.name} no pudo completarse.`
          }
          // Grounding: remember the LAST confirmed booking's real link so
          // the outgoing message can never carry a link the tool didn't
          // return. Ignore tool results that announced an error.
          if (tc.name === 'agendar_cita') {
            const parsed = extractBookingResult(output)
            if (parsed?.confirmado) realBooking = parsed
          }
          toolResults.push({
            role: 'tool',
            content: output,
            toolCallId: tc.id,
          })
        }
        // Append the assistant message carrying the requested tool_calls
        // plus the results so the model can reason over them on the next
        // round, then loop for a final reply.
        conversationMessages.push({
          role: 'assistant',
          content: result.text || '',
          toolCalls: result.toolCalls,
        })
        conversationMessages.push(...toolResults)
        continue
      }

      // No tool calls — this is the final text reply.
      finalText = result.text
      break
    }

    // The instant agendar_cita REALLY succeeded, the backend composes and
    // dispatches the confirmation itself — it must never depend on the
    // model's final echo (which can be empty or a handoff, leaving a
    // booked cita with NO WhatsApp message). Covers both cases: with link
    // (Google Meet) and — if the 5s timeout fired — the local-only
    // confirmation of the appointment already saved in the CRM.
    if (realBooking?.confirmado) {
      const deterministic = buildBookingConfirmationMessage(
        realBooking,
        contactCtx?.name,
      )
      if (deterministic) {
        finalText = deterministic
        toolFallback = null
      }
    }

    // The tool round must NOT be the end of the turn. Force one extra,
    // tool-free generation so the model turns the tool output (the Meet
    // link, the booked time) into a customer-facing confirmation even
    // when the round budget was exhausted by repeated tool calls.
    if (!finalText) {
      try {
        const final = await generateReply({
          config,
          systemPrompt,
          messages: conversationMessages,
        })
        finalUsage = final.usage ?? finalUsage
        finalText = final.text
      } catch (err) {
        console.error('[ai auto-reply] final confirmation pass failed:', err)
      }
    }

    // Last resort: if a scheduling tool failed and the model still said
    // nothing, send the fallback rather than going silent.
    if (!finalText && toolFallback) {
      finalText = toolFallback
    }

    // Anti-hallucination guard: the final message must be grounded in a
    // REAL tool result. Fake Meet/calendar URLs are replaced with the
    // returned link; a booking claim or an intermediate "un momento…"
    // without a real success never goes out. A wait-only phrase ("un
    // momento…") only skips that turn WITHOUT muting the conversation —
    // the next message is answered normally instead of leaving the chat
    // permanently silent.
    if (finalText) {
      const raw = finalText
      finalText = guardBookingReply(finalText, realBooking, {
        bookingContext: hasBookingIntent(messages),
      })
      const isWaitOnly =
        (INTERMEDIATE_ACK_RE.test(raw) || LINK_PROMISE_RE.test(raw)) &&
        !looksLikeBookingConfirmation(raw)
      if (finalText === null && isWaitOnly) {
        console.log(
          '[ai auto-reply] dropped an empty reply without a link (no handoff, no mute).',
        )
        return
      }
      if (finalText === null) {
        console.log(
          '[ai auto-reply] dropped an ungrounded text (no mute, no handoff).',
        )
        return
      }
    }

    // Record token spend on the account's BYO key.
    void logAiUsage(db, {
      accountId,
      conversationId,
      mode: 'auto_reply',
      provider: config.provider,
      model: config.model,
      usage: finalUsage,
    })

    // Si no hay texto final, no hay nada que enviar — pero JAMÁS se marca
    // la conversación como muda ni se la asigna a un humano
    // automáticamente: el siguiente mensaje se responde normal.
    if (!finalText) {
      console.log(
        '[ai auto-reply] no final text to send — skipping without muting.',
      )
      return
    }

    const { data: claimed, error: claimErr } = await db.rpc(
      'claim_ai_reply_slot',
      {
        conversation_id: conversationId,
        // 0 = ilimitado: el RPC claim_ai_reply_slot siempre otorga el slot.
        max_replies: 0,
      },
    )
    if (claimErr) {
      console.error('[ai auto-reply] claim_ai_reply_slot failed:', claimErr)
      return
    }
    if (claimed !== true) return

    const enviado = await engineSendAiReply({
      accountId,
      userId: configOwnerUserId,
      conversationId,
      contactId,
      text: finalText,
      aiGenerated: true,
      composeMessageId: args.composeMessageId,
      // La confirmación de una cita REAL va en UNA sola burbuja: se salta
      // el split por párrafos para que el cliente reciba la fecha, la hora
      // y el enlace de Meet juntos, sin cortes que puedan dejar el enlace
      // fuera o dividido en varios mensajes.
      single: realBooking?.confirmado === true,
    })
    console.log('[AUTO-REPLY] Mensaje enviado con éxito a WhatsApp:', enviado)
  } catch (err) {
    console.error('[ai auto-reply] dispatch failed:', err)
  }
}
